source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby 'replace_ruby_version'

# SmartMachine
gem 'smartmachine', "~> replace_smartmachine_version"
# Use Whenever for scheduling in scheduler
gem 'whenever', "~> 1.0"