#!/bin/sh

# oldrev, newrev, refname are a feature of the way in which Git executes the pre-receive hook.
# See https://www.kernel.org/pub/software/scm/git/docs/githooks.html
while read oldrev newrev refname; do
	# Only run this script for the master branch. You can remove this
	# if block if you wish to run it for others as well.
	if [ "$refname" == "refs/heads/master" ]; then

		echo "-----> Initializing Application"
		if [ $(git rev-parse --is-bare-repository) = true ]; then
		    REPOSITORY_BASENAME=$(basename "$PWD")
			REPOSITORY_BASENAME=${REPOSITORY_BASENAME%.git}
		else
		    REPOSITORY_BASENAME=$(basename $(readlink -nf "$PWD"/..))
		fi
		REPOSITORY_PATH=/apps/containers/${REPOSITORY_BASENAME}
		NOW_DATE=$(date +"%Y%m%d%H%M%S")
		[[ ! -d "$REPOSITORY_PATH/$NOW_DATE" ]] && mkdir -p $REPOSITORY_PATH/$NOW_DATE && git archive "$newrev" | tar -x -C $REPOSITORY_PATH/$NOW_DATE


		if [ -f $REPOSITORY_PATH/$NOW_DATE/bin/rails ]; then
			echo "-----> Ruby on Rails Application Detected"

			if [ ! -f "$REPOSITORY_PATH/$NOW_DATE/Procfile" ]; then
			echo "-----> Procfile not detected. Please add Procfile and try again."
				exit 1;
			fi

			if [ ! -f "$REPOSITORY_PATH/env" ]; then
				echo "-----> Generating Environment Variables File"
				cat > $REPOSITORY_PATH/env <<- EOF
					##### Docker
					VIRTUAL_HOST=$REPOSITORY_BASENAME.$DOMAIN_NAME
					# LETSENCRYPT_HOST=$REPOSITORY_BASENAME.$DOMAIN_NAME
					# LETSENCRYPT_EMAIL=admin@$DOMAIN_NAME
					# LETSENCRYPT_TEST=true

					##### Rails
					# RAILS_MASTER_KEY=testmasterkey
				EOF
			fi
		fi


		echo "-----> Launching Application"
		if [ "$(docker ps -a -q -f name=$REPOSITORY_BASENAME)" ]; then
			docker stop "$REPOSITORY_BASENAME" && docker rm "$REPOSITORY_BASENAME"
		fi
		docker create \
			--log-opt mode=non-blocking --log-opt max-buffer-size=4m \
			--name="$REPOSITORY_BASENAME" \
			--env-file="$REPOSITORY_PATH/env" \
			--volume="$APPS_ROOT/containers/$REPOSITORY_BASENAME/$NOW_DATE:/code" \
			--network="nginx-network" \
			--expose="5000" \
			--restart="always" \
			smartcloud/buildpacks/rails
		docker network connect solr-network $REPOSITORY_BASENAME
		docker start $REPOSITORY_BASENAME
		docker logs $REPOSITORY_BASENAME --follow
	fi
done